"""empty message

Revision ID: 386155b7315e
Revises: 72d0b38dd961
Create Date: 2020-07-07 01:34:10.071025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386155b7315e'
down_revision = '72d0b38dd961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('user_roles', 'decription')
    op.add_column('users', sa.Column('phone', sa.String(), nullable=False))
    op.drop_constraint('users_password_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_password_key', 'users', ['password'])
    op.drop_column('users', 'phone')
    op.add_column('user_roles', sa.Column('decription', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('user_roles', 'description')
    # ### end Alembic commands ###
