"""empty message

Revision ID: bddfcccb1c82
Revises: 386155b7315e
Create Date: 2020-07-19 21:08:41.650427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bddfcccb1c82'
down_revision = '386155b7315e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('price_amount', sa.Float(), nullable=True))
    op.drop_column('books', 'price_ammount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('price_ammount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('books', 'price_amount')
    # ### end Alembic commands ###
